### PR TITLE
Add benchmark results into README.md

### LINKED ISSUE #207: Add benchmark code for PLCC, SRCC, KRCC evaluation on MOS databases.
**Is your feature request related to a problem? Please describe.**
Now this code is available only for me and @snk4tr as part of another project. Propose to simplify it and add as a standalone script into the library, so that everyone could verify metric performance.

**Describe the solution you'd like**
Add `benchmark.py` file into `tests` folder with support for TID2013 and KADID10k databases evaluation.
Create README section with results.

**Additional context**
I've run all the tests locally and it seems that not all implementations from our library are now consistent with results from papers. Here is table for TID2013 database
Screenshot 2021-01-15 at 12 50 57

### PR DESCRIPTION
**Pull request by zakajd**
Closes #207 

## Proposed Changes
Huge redesign of README file
  - Deleted some shields
  - Changed metric list to table with release year, acronym and link to paper
  - Add benchmarking results

Add code for benchmarking performance in terms of SRCC and KRCC.

### CODE REVIEW

**Comment by zakajd** [comment]
Please check that everything is OK.
I deleted shields as discussed, but they still occupy 3 rows, don't know hot to fix this.

**Review by snk4tr — COMMENTED** [review]
Hey, great job @zakajd!
I fixed the problem with badges. 
Do you still plan to add another table, which shows the alignment of computation results with other implementations?

**Comment by zakajd** [comment]
@snk4tr I added table where results are compared with values stated in papers.It's in the README file 
 Do you want to also compare with other libraries, like `IQA-pytorch`?


image

**Comment by snk4tr** [comment]
@zakajd yes, I meant some comparison of not correlation score but actual output values. However, I am not sure whether they add something new if we already have this great table with correlation scores. That is why I asked. What do you think?

**Comment by zakajd** [comment]
@snk4tr  we have actual values for some metrics computed between `i01_00_05.bmp` <-> `I01.BMP` and `goldhill_jpeg` <-> `goldhill.jpeg` pairs, which can be found in tests. This can be mentioned somewhere in README, maybe right below the table?

**Comment by snk4tr** [comment]
@zakajd I am still not sure that this is a good idea. I think we could try to add them and revert in case if we don't like the result

**Comment by zakajd** [comment]
@snk4tr you want to add actual values computed on those 2 pairs of images into main README? 
This will make it too long and overcomplicated. I'm fine with values mentioned only in tests

It's better to create  `.md` file in `tests` section and make table there, if you think that's worth it.

**Review by snk4tr — APPROVED** [review]
Ok, looks really good so far 👍 
Merging.

**Pull request merged**
